name: "aws-secret-manager-to-dotenv-actions"
description: "GitHub Actions for AWS Secrets Manager - Convert AWS Secrets Manager key/value to .env file"
inputs:
  SECRET_NAME:
    description: "Set secret name that you want to get."
    required: true
  AWS_ACCESS_KEY_ID:
    description: "Set Aws Access Key ID"
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: "Set Aws Secret access Key"
    required: false
  AWS_SESSION_TOKEN:
    description: "Set Aws Session token Key"
    required: false
  AWS_DEFAULT_REGION:
    description: "Set Aws default region"
    required: false
  OUTPUT_PATH:
    description: "Set output file where variables are write"
    required: false
branding:
  icon: 'lock'
  color: 'orange'
runs:
  using: "node20"
  main: "dist/index.js"
